language: r
cache: packages
pandoc_version: 2.3.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

env:
  global:
    - secure: "Nun4l71Kj3DVDi26oD/ZXBILQ2j7AdrCIW7s0JgIPuZQ21UY3NrFIAd4EMNFuXG0U7yrVK8izpIfPgK9Zz4goU5BFgRC/lRkevrpQkd6KdB0+FQVXX9qpq08UC8Ko8/tTCUBCJgwfsH8HxxiN2LEB2S9juPkZOoqFMZfLdJZPtcARCjtKBg3zJf69bP/zlgGR3Vu4lUeZTnW1AmyEhiCYZE7t9yA/5hSlvFORtAagC7aqVtNozPXYcP4Ecr6Ju/MpCjx6pYFlXn7lzBKj4uLbhfke7ZK5wwkEYDhUaMMERCErsFvML0ZbCCBUvAtraBMRbIZYkHW46S+U2LTQKMBZNqy8pyr+u19hoObHqqZHFb9YgKxEKw4Gkwg2qCcceO0d4MhMqQ6YHRQVv11x0CW0EC/oTRHdrC0O+/iCnLw0XamyANaUFHjQr7bEyzdEebr0XIsxFbeoOGInC9pKtFo6hjRc9S+rRNH0ZwLU9Qkiw2amtxcE4Sf4sdj0ogYxPKmsZ8CN6uXXK61NOFaXbT/XFoJxlS6TcQVEc0rKpkze9VoErbGOTEJr5bUUx/10XI0PI80GauJJZ18f8ArOoGcys8gJxRzfPgWKrVEx72p7JiElpte0+gQGHpWPRHK9ip05VfuY8/DJpkNMWQl5igtLRsVvDWIz1KGB6z5Fukn7Gw="

addons:
  apt:
    packages:
      # Fonts
      - fonts-liberation
